"2022-11-10T21:04:14-0300" - main - INFO - ...Leyendo el archivo...
"2022-11-10T21:04:14-0300" - main - INFO - ...Archivo procesado...
"2022-11-10T21:05:37-0300" - main - INFO - ...Leyendo el archivo...
"2022-11-10T21:05:37-0300" - main - ERROR - No se pudo abrir el archivo
Traceback (most recent call last):
  File "/home/manu/desktop2/python/prismarun/unidades_2_15/tema4/functions/main.py", line 17, in <module>
    file = open("Exercise/cuento.txt", 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'Exercise/cuento.txt'
"2022-11-10T21:06:18-0300" - main - INFO - ...Leyendo el archivo...
"2022-11-10T21:06:18-0300" - main - INFO - ...Archivo procesado...
